# Numpy

## Using array function

In [6]:
import numpy as np
l=[[10,20,30],[40,50,60]]
a=np.array(l)
print(a)
print(a.ndim)

[[10 20 30]
 [40 50 60]]
2


In [7]:
t=(10,20,30,40,50)
a=np.array(t)
print(a)

[10 20 30 40 50]


In [9]:
t=('surendra','rahul','suraj','disha',50,88.2)
a=np.array(t)
print(a)

['surendra' 'rahul' 'suraj' 'disha' '50' '88.2']


# upcasting

In [10]:
a=np.array([90,999,555])
print(a.dtype)

int32


In [11]:
a=np.array([10,50,666,333])
print(a)
print(type(a))
print(a.dtype)

[ 10  50 666 333]
<class 'numpy.ndarray'>
int32


In [12]:
a=np.array([10,50,666,333.2])
print(a)
print(type(a))
print(a.dtype)

[ 10.   50.  666.  333.2]
<class 'numpy.ndarray'>
float64


In [13]:
a=np.array([10,50,666,333,40,30],dtype=float)
print(a)

[ 10.  50. 666. 333.  40.  30.]


In [14]:
a=np.array([10,50,666,333,40,30],dtype=complex)
print(a)

[ 10.+0.j  50.+0.j 666.+0.j 333.+0.j  40.+0.j  30.+0.j]


In [16]:
a=np.array([10,50,666,333,40,0],dtype=bool)
print(a)

[ True  True  True  True  True False]


In [17]:
a=np.array([10,50,66.6,333.6,40.2,30],dtype=int)
print(a)

[ 10  50  66 333  40  30]


In [18]:
a=np.array(True+True,dtype=str)
print(a)

2


In [19]:
a=np.array(str(True+True)+'hello')
print(a)

2hello


In [20]:
a=np.array([10,50,'hello',56.8,True])
print(a)
print(a.dtype)

['10' '50' 'hello' '56.8' 'True']
<U32


In [21]:
a=np.array([10,50,'hello',56.8,True],dtype=object)
print(a)
print(a.dtype)

[10 50 'hello' 56.8 True]
object


# arange() function

In [24]:
a=np.arange(10,50,1)
print(a)
print(a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32


In [26]:
a=np.arange(10.,50.,2) #(start,stop,step)
print(a)
print(a.dtype)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48.]
float64


# linspace() function 

# print(help(np.linspace))

In [30]:
a=np.linspace(0,50)
print(a

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


In [33]:
a=np.linspace(0,50,num=6)
print(a)

[ 0. 10. 20. 30. 40. 50.]


In [34]:
a=np.linspace(0,50,num=6,dtype=int)
print(a)

[ 0 10 20 30 40 50]


In [37]:
a=np.linspace(0,50,num=3,endpoint=False)
print(a)

[ 0.         16.66666667 33.33333333]


In [38]:
a=np.linspace(0,50,num=3,endpoint=True)
print(a)

[ 0. 25. 50.]


In [39]:
a=np.linspace(0,50,num=3,retstep=False)
print(a)

[ 0. 25. 50.]


In [41]:
a=np.linspace(0,50,num=6,retstep=True)
print(a)

(array([ 0., 10., 20., 30., 40., 50.]), 10.0)


# zeros()function

In [42]:
print(help(np.zeros))

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [45]:
a=np.zeros(5)
print(a)
#zeros(shape, dtype=float, order='C', *, like=None)

[0. 0. 0. 0. 0.]


In [44]:
a=np.zeros((5,),dtype=int)
print(a)

[0 0 0 0 0]


In [46]:
a=np.zeros((5,2),dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [47]:
s=(3,3)
np.zeros(s)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

# multidimentional array

In [51]:
s=(3,5,3)
np.zeros(s)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# ones() function 

In [52]:
print(help(np.ones))

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

In [54]:
a=np.ones((5,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# full() function

In [55]:
print(help(np.full))

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passe

In [61]:
a=np.full((10),100)
print(a)

[100 100 100 100 100 100 100 100 100 100]


In [63]:
a=np.full((2, 2), np.inf)#infinity
print(a)

[[inf inf]
 [inf inf]]


In [64]:
a=np.full((2, 2), [1, 2])
print(a)

[[1 2]
 [1 2]]


# eye() function

In [65]:
print(help(np.eye))

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [66]:
a=np.eye(2, dtype=int)
print(a)

[[1 0]
 [0 1]]


In [71]:
a=np.eye(3,3 ,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [72]:
a=np.eye(6,6,2,dtype=int)
print(a)

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [73]:
a=np.eye(6,6,-1,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [74]:
a=np.eye(6,6,-2,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


# indentity() function

In [75]:
print(help(np.identity))

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            The ``like`` keyword is an experimental feature pending on
            acceptance of :ref:`NEP 35 <NEP35>`.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` 

In [80]:
a=np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


# empty() function

In [81]:
print(help(np.empty))

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [88]:
a=np.empty([2, 5], dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [89]:
a=np.empty([3, 3])
print(a)

[[4.94065646e-324 0.00000000e+000 0.00000000e+000]
 [2.12199579e-314 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.94065646e-324 0.00000000e+000]]


In [5]:
import numpy as np

# random()function

In [6]:
print(help(np.random.rand))

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

# rand() function
rand() and unifrom() is uniform distribution.

In [7]:
a=np.random.rand()
print(a)

0.47183070422596063


In [9]:
a=np.random.rand(4,3)
print(a)

[[0.29111263 0.34229621 0.24807226]
 [0.27209583 0.37778137 0.20064792]
 [0.23124311 0.27385403 0.5450393 ]
 [0.27275245 0.52499065 0.86324945]]


In [10]:
a=np.random.rand(2,4,3)
print(a)

[[[0.83395887 0.24740667 0.12437186]
  [0.0249295  0.13877286 0.28219092]
  [0.6491227  0.98463754 0.62556397]
  [0.58648699 0.60795137 0.85738038]]

 [[0.73433933 0.67434863 0.54283751]
  [0.90460105 0.44040012 0.138994  ]
  [0.33929908 0.52849823 0.28575212]
  [0.04439388 0.89143453 0.18441769]]]


# uniform() function

In [11]:
print(help(np.random.uniform)) #doubt

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the ``uniform`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high.  The default value is 1.0.
    size 

In [13]:
a = np.random.uniform(-1,0,10)
print(a)

[-0.13668497 -0.83179588 -0.63466992 -0.12114268 -0.20358307 -0.12371886
 -0.40035857 -0.04263958 -0.5715947  -0.01126346]


# randint()
to generate random intger.

In [14]:
print(help(np.random.randint))

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [15]:
a=np.random.randint(2, size=10) #limt,size
print(a)

[0 1 1 0 1 0 0 1 0 1]


In [16]:
a=np.random.randint(1, size=10)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [18]:
#Generate a 2 x 4 array of ints between 0 and 4, inclusive:
a=np.random.randint(5, size=(2, 4))
print(a)

[[4 2 0 4]
 [0 2 1 2]]


In [20]:
#Generate a 1 x 3 array with 3 different upper bounds
a=np.random.randint(1, [3, 5, 10]) #doubt
print(a)

[1 2 7]


In [22]:
#Generate a 1 by 3 array with 3 different lower bounds
a=np.random.randint([1, 5, 7], 10) #doubt
print(a)

[8 6 8]


In [23]:
#Generate a 2 by 4 array using broadcasting with dtype of uint8
a=np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8) #doubt
print(a)

[[ 7  3  7  9]
 [18  3  9 12]]


# randn() function
randn() and normal() is normal distribution.

In [24]:
print(help(np.random.randn))

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [25]:
a=np.random.randn()
print(a)

-1.119105501967648


In [29]:
a=0*np.random.randn(2,3)
print(a)

[[ 1.58434481 -0.95677752 -2.91414775]
 [ 1.60359438  2.28190851 -3.10021407]]


# normal() function

In [31]:
print(help(np.random.normal)) #doubts

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution